name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '**'  # Change this to your default branch if it's not `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: code/fe/portfolio

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'  # Use the version that matches your project

      - name: corepack enable
        run: corepack enable
        
      - name: corepack prepare yarn
        run: corepack prepare yarn@4.3.0 --activate

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: yarn nx build landing-page

      - name: List current folder
        run: ls

      - name: List dist folder
        run: ls dist/apps/landing-page
        

      - name: Deploy to GitHub Pages
        run: yarn nx deploy landing-page
        working-directory: code/fe/portfolio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
